nodeLinker: node-modules
enableGlobalCache: true
nmMode: hardlinks-local

packageExtensions:
  react-scripts@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "@uniswap/eslint-config@*":
    peerDependencies:
      eslint: "*"
      typescript: "*" 